---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helloproperties
data:
  application.yml: |
    management:
      endpoints:
        web:
          exposure:
            include: health,info,configprops
    spring:
      security:
        user:
          roles: ACTUATOR
